language: ruby

install:
  - bundle install
cache:
  bundler: true 

jobs:
  include:
    - stage: danger
      name: "Danger"
      script: bundle exec danger --fail-on-errors=true
    - stage: lint-tests
      name: "Lint & tests"
      script: bundle exec rake lint
    - # Lint & tests
      script: bundle exec rake build   
    - stage: deploy
      script: bundle exec rake install && ruby ./bin/gem-release.rb

stages:
  - name: danger
    if: type IN (pull_request)
  - name: lint-tests
    if: type IN (push, pull_request)
  - name: deploy
    if: tag IS present